#version 460 core 

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430) buffer;
layout(binding = 0) buffer b_startPos { vec4 startPos[]; };
layout(binding = 1) buffer b_endPos { vec4 endPos[]; };
layout(binding = 1) buffer b_damping { float damping[]; };

uniform uint N;

void main()
{   
    uint i = gl_GlobalInvocationID.x;
    uint j = gl_GlobalInvocationID.y;
    uint BI = i * N + j;

    startPos[BI].y = damping[BI]; 
}